revision 1
SwissBitcoinPay/nopcommerce-plugin pull request #1
Opened 2023-09-23 16:30 UTC by Nisaba

2023-09-24 09:21 UTC, SwissBitcoinPay commented
At the "Payment method" selection page, is there a way to change this logo to something more generic like "Bitcoin Lightning" ?
![image](https://github.com/SwissBitcoinPay/nopcommerce-plugin/assets/128961268/6ca603a1-77e7-4a41-99b3-4a08c6e0d894)

Replace it with like:
![image](https://github.com/SwissBitcoinPay/nopcommerce-plugin/assets/128961268/60623ca2-14fc-4814-84db-01f724c2bd92)

2023-09-24 09:31 UTC, SwissBitcoinPay reviewed
Some typos and description improvement

2023-09-24 09:31 UTC, SwissBitcoinPay commented on SwissBitcoinPaySettings.cs
> +        /// Your Swiss Bitcoin Pay API Key given in your Swiss Bitcoin Pay dashbord
Tiny typo :)

```suggestion
        /// Your Swiss Bitcoin Pay API Key given in your Swiss Bitcoin Pay dashboard

```

2023-09-24 09:31 UTC, SwissBitcoinPay commented on SwissBitcoinPaySettings.cs
> +        /// The Api Secret value set in your Swiss Bitcoin Pay dashbord
Tiny typo :)

```suggestion
        /// The Api Secret value set in your Swiss Bitcoin Pay dashboard

```

2023-09-24 09:31 UTC, SwissBitcoinPay commented on plugin.json
> +  "Description": "This plugin enables Bitcoin payment with Swiss Bitcoin Pay"
More specific description

```suggestion
  "Description": "This plugin enable Bitcoin Onchain/Lightning payments with Swiss Bitcoin Pay"

```

2023-09-24 16:19 UTC, Nisaba commented on SwissBitcoinPaySettings.cs
> +        /// The Api Secret value set in your Swiss Bitcoin Pay dashbord
ok done

2023-09-24 16:20 UTC, Nisaba commented on plugin.json
> +  "Description": "This plugin enables Bitcoin payment with Swiss Bitcoin Pay"
ok done

2023-09-26 18:55 UTC, SwissBitcoinPay commented on SwissBitcoinPayPaymentProcessor.cs
> +                ["Plugins.Payments.SwissBitcoinPay.PaymentMethodDescription"] = "Pay in bitcoins with Swiss Bitcoin Pay",
```suggestion
                ["Plugins.Payments.SwissBitcoinPay.PaymentMethodDescription"] = "Pay in Bitcoin with Swiss Bitcoin Pay",

```

2023-09-26 18:55 UTC, SwissBitcoinPay requested changes
Last change

2023-09-27 12:58 UTC, merged